### ISSUE TITLE
Creating a Website with Vue.js backed by Google Sheets - Albert Au Yeung

### ISSUE THREAD

**Issue by albertauyeung** [albertauyeung/albertauyeung.github.io#3]
https://albertauyeung.github.io/2020/04/26/vuejs-google-sheets.html 

 It has been quite a long time since I have developed a Website. The last one I made was probably the Website that I designed and developed for my brother (ht...

**Comment by CynthiaBlue** [comment]
Do you have any tutorials on how to use Vue to push data into a Google Spreadsheet?
