### ISSUE TITLE
Generating N-grams from Sentences in Python - Albert Au Yeung

### ISSUE THREAD

**Issue by albertauyeung** [albertauyeung/albertauyeung.github.io#6]
https://albertauyeung.github.io/2018/06/03/generating-ngrams.html 

 N-grams are contiguous sequences of n-items in a sentence. N can be 1, 2 or any other positive integers, although usually we do not consider very large N bec...

**Comment by Martinsbane** [comment]
Awesome, is there a way you can count the occurrence of a word or phrase after generating n-grams?

**Comment by albertauyeung** [comment]
@Martinsbane you can use the `CountVectorizer` in `scikit-learn` to do that (https://scikit-learn.org/stable/modules/generated/sklearn.feature_extraction.text.CountVectorizer.html).

**Comment by Martinsbane** [comment]
Thanks a lot, kind of a noob and don't know my way around.
Thanks again
