### ISSUE TITLE
BERT - Tokenization and Encoding - Albert Au Yeung

### ISSUE THREAD

**Issue by albertauyeung** [albertauyeung/albertauyeung.github.io#8]
https://albertauyeung.github.io/2020/06/19/bert-tokenization.html 

 To use a pre-trained BERT model, we need to convert the input data into an appropriate format so that each sentence can be sent to the pre-trained model to o...

**Comment by XM-WANG** [comment]
Nice tutorial !
It seems miss a "z" at <t.convert_tokens_to_ids(["characteristically"])> in the Converting Tokens to IDs part

**Comment by kamwoh** [comment]
bert tokenizer has done a very good job on separating the word into subwords, I always wonder how to handle individual number in string e.g. 12345, 45678. bert separate the number into subwords
e.g.
12345 --> 123, ##45
45678 --> 45, ##6, ##7, ##8

**Comment by albertauyeung** [comment]
> @kamwoh
> bert tokenizer has done a very good job on separating the word into subwords, I always wonder how to handle individual number in string e.g. 12345, 45678. bert separate the number into subwords
> e.g.
> 12345 --> 123, ##45
> 45678 --> 45, ##6, ##7, ##8

I think there are several ways to deal with numbers, such as:
- simply removing the tokens that contain only digits
- convert all numbers into the same placeholder and assign the same label to that

I think that depends on whether the numbers are important in your use case.
